### ISSUE TITLE
--root option is obsolete

### ISSUE THREAD

**Issue by mrvik** [kitsunyan/pakku#13]
Using pakku 0.12-3.
````
 mrvik@mrvik~% pakku -V
advertencia: la opción --root está obsoleta; a partir de ahora es --sysroot


                       Pakku v0.12
                       Copyright (C) 2018 kitsunyan

 .--.                  Pacman v5.1.0 - libalpm v11.0.0
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2018 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       Este programa puede distribuirse libremente bajo
                       los términos de la licencia GNU General Public License
````
The first line appears in every command where `pakku` runs `pacman`

**Comment by kitsunyan** [comment]
Yes, I know. Actually, not in every command, but only in the first one which is used to test that arguments are correct https://github.com/kitsunyan/pakku/blob/921c83730f425dfb6b7db459044db839124dcff4/src/pacman.nim#L387. Right now I don't have time to fix it, the problem is quite more complex that it seems.

**Comment by kitsunyan** [comment]
Fixed! https://github.com/kitsunyan/pakku/commit/de157edb51e1131f8215cc22931c006b9adf3803

**Comment by kitsunyan** [comment]
Pakku supports `--root` option despite that it's deprecated. And will support it until it will be completely removed.
