### ISSUE TITLE
Is there a way to disable fetching AUR comments ?

### ISSUE THREAD

**Issue by BurhanDanger** [kitsunyan/pakku#20]

**Comment by kitsunyan** [comment]
You can remove `AurComments` option from config file.

**Comment by BurhanDanger** [comment]
Is there a pakku cmd option for that i.e. pakku --AurComment=yes/no ?

One more question why pakku have only systemwide configuration? Every update resets pakku.conf and saves to .pacsave. Is it possible to have it such way pakku loads 
~/.config/pakku/pakku.conf , if not present then load /etc/pakku.conf.

**Comment by kitsunyan** [comment]
No, there isn't. But I think I can add it. I just not sure why somebody need it. If you need AUR comments, just enable the option and don't read them when you don't need them.

It shouldn't reset unless you switch between `pakku` and `pakku-git`. When you just upgrade between versions, it will create a .pacnew file and you can just merge your changes. In case of user configurations, you'll need to merge new options as well, there is no difference.

I won't add a user config file since pakku is a system tool (`pakku(8)`) and user's dirs are used only for makepkg-related operations.
