### ISSUE TITLE
Use Nim's httpclient instead of libcurl

### ISSUE THREAD

**Issue by Yardanico** [kitsunyan/pakku#22]
Hello, amazing project (and the fact that it's written in Nim is even more amazing!) :)

I have a question - why did you wrap libcurl instead of using Nim's `httpclient` stdlib module? It only depends on sockets and openssl (for SSL)

**Comment by kitsunyan** [comment]
I found that Nim's httpclient can't load some URLs when I tried to use it (I don't remember the exact reason). Also, it increased the size of binary by 2 times. And… I wanted to try to create my own bindings since it was my first Nim project.

I don't think that there is something bad in using libcurl.

**Comment by Yardanico** [comment]
@kitsunyan did you try to use strip to make binary smaller?
And why it's bad - well, it's yet another third-party dependency :)

**Comment by kitsunyan** [comment]
> did you try to use strip to make binary smaller?

Yes. And I noticed the increase after stripping.

> And why it's bad - well, it's yet another third-party dependency :)

That's normal when package depends on another package being more lightweight. Shared libraries were designed for this. Also, pacman itself depends on curl as well as git.
