### ISSUE TITLE
AArch64 - error: repo 'aur' can not be used as fake AUR repository

### ISSUE THREAD

**Issue by WebReflection** [kitsunyan/pakku#43]
After successfully building on RPi3, any `pacman -Ss packge` search would fail with the message in this ticket title.

Others packages seems to work fine, including `yaourt` and `yay`.

Please let me know if you need any other detail, thanks.

**Comment by kitsunyan** [comment]
You can rename fake AUR repo name using `AurRepo` config option.

**Comment by WebReflection** [comment]
@kitsunyan and why wouldn't this be part of the PKGBUILD ? it works fine in x86_64, not sure why one would need extra steps on Arch64 🤔

**Comment by kitsunyan** [comment]
This problem is not related to aarch64 but to Arch Linux ARM, which supports multiple architectures.

**Comment by WebReflection** [comment]
OK, but how `yaourt` and `yay` work out of the box?

I'm just asking what's the procedure to make pakku useful on ArchLinuxARM too so I can auto/enable AUR while installing it from [archibold.io/install/pakku](https://github.com/WebReflection/archibold.io/blob/gh-pages/install/pakku)

**Comment by kitsunyan** [comment]
> OK, but how yaourt and yay work out of the box?

I don't know for sure how they work. Pacman allows to specify repository before package name: `pacman -S repo/pkgname`, so you could install the package from specific repo when the package is available on multiple repos. For AUR pakku uses fake "aur" repo so you could use it in the same commands as well (`pakku -S aur/pkgname`).

But what if you add "aur" repo in `pacman.conf` and, furthermore, this repo will contain the packages built from AUR? In order to resolve ambiguity, I decided to not allow fake repo to be named as existing repository. Instead, I added a config option to rename fake repo.

> I'm just asking what's the procedure to make pakku useful on ArchLinuxARM too so I can auto/enable AUR while installing it from archibold.io/install/pakku

I think you can just set `AurRepo` to something else (feel free to come up with the name yourself) in `pakku.conf` during `prepare`.
