### ISSUE TITLE
[Question|Feature Request] Is there a way to preserve temp directory

### ISSUE THREAD

**Issue by BurhanDanger** [kitsunyan/pakku#9]
I set ``TmpDir = ~/.cache/pakku`` . Now whenever I build and install from aur this directory vanishes. I kind of need these files. This helps me quickly install previous version of a package. Or review the changes that I made in the previous pkgbuild.

I'd very much like if the files are not permanently deleted after each build.

IF POSSIBLE:
I propose you create another variable eg ``preserveDir`` which when non-empty moves the successfully build package-folder to the directory. When empty files will be deleted.
This can help faster building in ram-disk, also depending on user choice when/if needed files will be there.

**Comment by kitsunyan** [comment]
I don't like the idea of preserving build directory since it may (or may not) contain build files (`src`), package files (`pkg`) and all source files (tarballs, bare git repos, etc).

In your case, I think preserving _built packages_ and preserving _modified files_ are different tasks. I already thought about preserving built packages, copying them to `/var/cache/pacman/pkg`. This process is regular for pacman and you can always clean the dir using `-Sc` operation.

Speaking about preserving modified files, I think I can add an option to run post-build script (as I did in https://github.com/kitsunyan/pakku/issues/5) in which you can save necessary files youself, or even run `git diff .` and save the changes as patch file (all package build directories are git directories).

What do you think?

**Comment by BurhanDanger** [comment]
> it may (or may not) contain build files (src), package files (pkg) and all source files (tarballs, bare git repos, etc).

Yeah . These are pretty pointless to store.
>  I already thought about preserving built packages, copying them to /var/cache/pacman/pkg

This'd be great. It'd make cleaning easy by using ``paccache.hook`` with content like ``paccache -rk1 -ruk0``. 

> Speaking about preserving modified files, I think I can add an option to run post-build script (as I did in #5) in which you can save necessary files youself, or even run git diff . and save the changes as patch file 

Not sure about this. Your pre-build script runs just before makepkg , right. I need to save files as before running makepkg. As you said after makepkg comes some unnecessary files, which I'd need to exclude anyway. So pre-build script enough ?

**Comment by kitsunyan** [comment]
> Not sure about this. Your pre-build script runs just before makepkg , right. I need to save files as before running makepkg. As you said after makepkg comes some unnecessary files, which I'd need to exclude anyway. So pre-build script enough ?

No, I'm talking about new option — _post-build_ script, which will be executed _after_ build.

**Comment by BurhanDanger** [comment]
It'd be great to have post-build command. But I'm thinking for saving _modified_ files pre-build script is enough. Like e.g ``PreBuildCommand = git diff . > /path/to/file``

**Comment by kitsunyan** [comment]
Oh, I forgot that pre-build command is executed after "view files" ask! So it should be enough.

**Comment by kitsunyan** [comment]
Done! Built packages are copied to `/var/cache/pacman/pkg`. https://github.com/kitsunyan/pakku/commit/9c7c88d41a3a4f59602f1e4b42635551379ccc99

I hope my decision about preserving modified files suits you.

**Comment by BurhanDanger** [comment]
Sorry to bother you again. 

- Will you make this directory(aur pkg store-dir) configurable? 

- It asks for sudo password (for ``cp``) even if I set ``CacheDir`` to some user home directory eg. ``CacheDir    = ~/.cache/pakku/pkg/`` in pacman.conf. Is this normal ?

**Comment by kitsunyan** [comment]
I think in the future when some functions will be implemented in user's cache directory (e.g. support for `--devel` flag), I'll make it configurable.

It asks, but it will ask since pacman will copy to cache dir only as root. Also, it asks the password not for `cp` only, but for `pacman -U` as well (it was implemented as `install.nim` executable which does these calls).

**Comment by kitsunyan** [comment]
So, this directory is configurable now. At least you can configure `UserCacheDir`. All built packages will be stored to `${UserCacheDir}/packages` if you set `PreserveBuilt` option to `User` in config file. https://github.com/kitsunyan/pakku/commit/80b7087c8f8995cbadd038661b0dcdd39c7d08d5
